### ISSUE TITLE
Filter/Export

### ISSUE THREAD

**Issue by risturiz** [AntonKhorev/osm-note-viewer#1]
Hi, pretty great app to work with Notes... Im wondering if you can filter by country? ( select only user notes country specific ). And the other question is about export Notes like Geojson?

Thanks a lot!

**Comment by AntonKhorev** [comment]
Filter by country - not yet, depends on what you mean by it:

- if it's downloading notes only for a specific country: There's no easy way to get them though the api, geographically it can limit the selection only by bounding boxes. I plan to implement getting note ids from arbitrary xml feeds which is going to make it possible to use [Pascal Neis' note feeds](https://resultmaps.neis-one.org/osm-notes) for a specific country. But that won't let you see all of the user's notes.
- if it's hiding part of downloaded notes not belonging to a country using the *Filter* form: I'd have to either store country boundaries or ask Nominatim or similar service for a boundary... In the latter case it could be not just a country boundary but any kind of a boundary. Then I'd have to come up with a filter syntax for note locations. Current filter implementation only works with comments.

**Comment by risturiz** [comment]
The general idea is to simplify working with notes... We are doing something like a Mapathon but with Notes ( Notathon )[1], and having an app like "osm-note-viewer" help a lot because we can organize better the notes resolution ( export / filter / etc ). Maybe in the future we can export Notes directly to "Divide and Map"[2] to help with this task.

[1] https://www.openstreetmap.org/user/AngocA/diary/399317 
[2] https://www.damn-project.org/

Thanks for your great work!

**Comment by AntonKhorev** [comment]
Added GeoJSON selected notes export similar to GPX export.

**Comment by AntonKhorev** [comment]
Added showing API requests when *Show request parameters and URLs* checkbox is checked. It prints links with API requests under *Fetch notes* and *Load more* buttons. For *Fetch notes* there are links for data in various formats like xml and rss.

Like I said [earlier](https://github.com/AntonKhorev/osm-note-viewer/issues/1#issuecomment-1147432768), it can function as kind export with data exported directly from the OSM API. It may be enough if you don't use the filter or note checkboxes inside note-viewer and set the limit high enough to download all the notes you're interested in.

**Comment by AntonKhorev** [comment]
Added this:
> I plan to implement getting note ids from arbitrary xml feeds which is going to make it possible to use [Pascal Neis' note feeds](https://resultmaps.neis-one.org/osm-notes) for a specific country. But that won't let you see all of the user's notes.

Use *Load an XML file* dialog above the filter. Later I'll make tabs to switch between different download dialogs.

**Comment by AntonKhorev** [comment]
Added tabs.

**Comment by risturiz** [comment]
> Added tabs.

Awesome tabs upgrade :-)

**Comment by risturiz** [comment]
Hi, closing this... Thanks a lot!!
