### ISSUE TITLE
syntax for comment filter

### ISSUE THREAD

**Issue by Marc-marc-marc** [AntonKhorev/osm-note-viewer#5]
this filter
```
*
text != "#survey"
```
doesn't hide note with an opening text "#survey" nor commented with it.
tested with https://www.openstreetmap.org/note/3708726
tested also with
```
^
text != "#survey"
```
but it doesn't work either
What's wrong with my syntax?

**Comment by AntonKhorev** [comment]
You're asking for a negative substring match, which I haven't done yet.

**Comment by AntonKhorev** [comment]
Added negative substring match, this should work now:

```
^
text !~= "#survey"
```

**Comment by Marc-marc-marc** [comment]
Thanks. but it produce a "syntax error"

**Comment by AntonKhorev** [comment]
Are you on the latest version?
![image](https://github.com/user-attachments/assets/3f6a3000-5dd6-4730-bd55-ef9f52ff838e)

If not, try reloading the webpage.
